### PR TITLE
Use listenTo instead of direct model binding

### PR DESCRIPTION
**Pull request by ogonkov**
http://backbonejs.org/#Events-listenTo

### CODE REVIEW

**Comment by uzikilon** [comment]
To my understanding the reason `listenTo` is preferred over `on` is because we can later use `stopListening` to unsubscribe, which we are not doing here.
Unless there's something I am missing, this commit will be trading support for BB < 0.9 for no added value.
Can you explain the value?

**Comment by ogonkov** [comment]
@uzikilon `listenTo` also guaranteed clearing your callbacks from model to prevent leakage.

**Comment by ogonkov** [comment]
I just look at the code, i think `stop` method should also clear `this.model` reference. Or here should be real `destroy` method for clearing it.

**Comment by uzikilon** [comment]
Okay, does https://github.com/uzikilon/backbone-poller/pull/38 make sense to you?

**Comment by ogonkov** [comment]
Looks good, but docs should be also updated with new method, i think.

**Comment by ukilon-okta** [comment]
Fixed with #38

**Comment by uzikilon** [comment]
Fixed with #38

**Comment by uzikilon** [comment]
Thank you for the contribution

**Comment by ogonkov** [comment]
Thank you for great lib!

**Pull request closed without merging**
